version: '3.1'

services:
  pg_db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=test
      - POSTGRES_DB=testdb
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
  redis:
    image: redis:alpine
    command: redis-server --requirepass Redis2019!
    ports:
      - '6379:6379'
